config/routes.rb
SimpleForum::Application.routes.draw do

  root :to => 'home#index'

  resources :sections, :shallow => true do
    resources :forums, :shallow => true do
      resources :topics, :shallow => true do
        resources :posts
      end
    end
  end

  devise_for :users, :path => "", :controllers => { :registrations => "registrations" },
             :path_names => {  :sign_in => 'login',
                               :sign_out => 'logout',
                               :password => 'secret',
                               :confirmation => 'verification',
                               :unlock => 'unblock',
                               :registration => 'register',
                               :sign_up => 'sign_up' }

  resources :users do
    resources :assets
  end

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  validates :title, :presence => true

  belongs_to :section
  has_many :topics, :dependent => :destroy
  has_many :posts, :dependent => :destroy
  has_one :last_post, :class_name => "Post", :order => "updated_at DESC"

end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_filter :find_section, :only => [:new, :create]

  load_and_authorize_resource

  def show
    @topics = @forum.topics.includes(:user, :last_post => :user).order("id DESC").page params[:page]
    respond_to do |format|
      format.html
    end
  end

  def new
    @forum = @section.forums.build

    respond_to do |format|
      format.html
    end
  end

  def edit
  end

  def create
    @forum = @section.forums.build(params[:forum])
    respond_to do |format|
      if @forum.save
        format.html { redirect_to(root_path, :notice => 'Forum was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @forum.update_attributes(params[:forum])
        format.html { redirect_to(root_path, :notice => 'Forum was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy

    @forum.destroy

    respond_to do |format|
      format.html { redirect_to(forums_url) }
    end
  end

  private

  def find_section
    @section = Section.find(params[:section_id])
  end
end

app/views/forums/_form.html.haml
= form_for [@section, @forum] do |f|
  -if @forum.errors.any?
    #error_explanation
      %h2= "#{pluralize(@forum.errors.count, "error")} prohibited this forum from being saved:"
      %ul
        - @forum.errors.full_messages.each do |msg|
          %li= msg

  .title
    .left= f.label :title
    .left= f.text_field :title
    .clear
  = f.label :description
  = f.text_area :description, :class => "kind_editor", :id => "kind_editor"
  = f.submit 'Save'
= render "shared/editor"

app/views/forums/_forum.html.haml
= div_for forum do
  .forum_image= show_icon_by_post(forum.last_post, "forum_new.gif", "forum.gif")
  .forum_title
    = link_to forum.title, forum
    .forum_description= raw forum.description
  .forum_topic= "#{forum.topics.size} Topics"
  .forum_post= "#{forum.posts.size} Posts"
  .forum_last
    - if post = forum.last_post
      = link_to(post.user.user_name, post.user)
      .date= link_to(time_ago_in_words(post.updated_at), topic_path(post.topic_id)+"#post_#{post.id}")
    - else
      N/A
      .date N/A
  .clear

app/views/forums/edit.html.haml
.topic_posts
  #topic_posts_content
    .topic
      .author= user_info(current_user)
      .content
        = render 'form'
      .clear

app/views/forums/new.html.haml
.topic_posts
  #topic_posts_content
    .topic
      .author= user_info(current_user)
      .content
        = render 'form'
      .clear

app/views/forums/show.html.haml
.forum_top
  .title
    %h2= @forum.title
    .left.description.edit= "[#{@forum.topics.size} Topics / #{@forum.posts.size} Posts]"
    - if can? :update, @forum
      .edit.tool= link_to 'Edit', edit_forum_path(@forum)
  .clear
  .description= raw @forum.description
  .left= paginate @topics
  - if can? :create, Topic
    .right.tool= link_to 'New Topic', new_forum_topic_path(@forum)
  .clear
.forum_body
  .top
    .title Title
    .author Author
    .count Reply/Browse
    .post Last Post
    .clear
  = render @topics
  = paginate @topics