config/routes.rb
SimpleForum::Application.routes.draw do

  root :to => 'home#index'

  resources :sections, :shallow => true do
    resources :forums, :shallow => true do
      resources :topics, :shallow => true do
        resources :posts
      end
    end
  end

  devise_for :users, :path => "", :controllers => { :registrations => "registrations" },
             :path_names => {  :sign_in => 'login',
                               :sign_out => 'logout',
                               :password => 'secret',
                               :confirmation => 'verification',
                               :unlock => 'unblock',
                               :registration => 'register',
                               :sign_up => 'sign_up' }

  resources :users do
    resources :assets
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, :presence => true
  validates :content, :presence => true

  has_many :posts, :dependent => :destroy
  has_one :last_post, :class_name => "Post", :order => "updated_at DESC"

  belongs_to :forum, :counter_cache => true
  belongs_to :user

  paginates_per 20

  def browse_once
    Topic.update_all ['browse_count = ?', (self.browse_count + 1)], ['id = ?', self.id]
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  load_and_authorize_resource

  before_filter :find_forum, :only => [:new, :create]

  def show
    @topic.browse_once
    @posts = @topic.posts.includes(:forum, :user => :roles).page params[:page]
    @post = Post.new
    respond_to do |format|
      format.html
    end
  end

  def new
    @topic = @forum.topics.build
    respond_to do |format|
      format.html
    end
  end

  def edit

  end


  def create
    @topic = @forum.topics.build(params[:topic])
    @topic.user = current_user

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @forum, notice: 'Topic was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to @topic.forum }
    end
  end

  private

  def find_forum
    @forum = Forum.find(params[:forum_id])
  end
end

app/views/topics/_form.html.haml
= form_for [@forum, @topic] do |f|
  -if @topic.errors.any?
    #error_explanation
      %h2= "#{pluralize(@topic.errors.count, "error")} prohibited this topic from being saved:"
      %ul
        - @topic.errors.full_messages.each do |msg|
          %li= msg

  .title
    .left= f.label :title
    .left= f.text_field :title
    .clear
  = f.text_area :content, :class => "kind_editor", :id => "kind_editor"
  = f.submit 'Save'

= render "assets/upload_tool"
= render "shared/editor"

app/views/topics/_topic.html.haml
.body
  .topic_image= link_to show_icon_by_post(topic.last_post, "folder_new.gif", "folder_common.gif"), topic, :target => "_blank"
  .title
    .left= link_to topic.title, topic
    - if can? :manage, topic
      .tool= link_to "Delete", topic, :method => :delete, :confirm => "Are you sure?"
  .author
    = link_to topic.user.user_name, topic.user
    %br/
    .date= topic.created_at.to_date
  .count
    = topic.posts.size
    .date= topic.browse_count
  .post
    - if post = topic.last_post
      = link_to post.user.user_name, post.user
      .date= link_to(time_ago_in_words(post.updated_at), topic_path(post.topic_id)+"#post_#{post.id}")
    - else
      N/A
      .date N/A
  .clear

app/views/topics/edit.html.haml
.topic_posts
  #topic_posts_content
    .topic
      .author= user_info(current_user)
      .content
        = render 'form'
      .clear

app/views/topics/new.html.haml
.topic_posts
  #topic_posts_content
    .topic
      .author= user_info(current_user)
      .content
        = render 'form'
      .clear

app/views/topics/show.html.haml
.topic_posts
  #topic_posts_content
    .topic
      .author= user_info(@topic.user)
      .content
        .title= @topic.title
        .top
          .right= "Published at #{@topic.created_at.to_date}"
          - if can? :update, @topic
            .left.tool= link_to "Edit", edit_topic_path(@topic)
          - if can? :manage, @topic
            .left.tool= link_to "Delete", @topic, :method => :delete, :confirm => "Are you sure?"
          .clear
        - if @topic.created_at != @topic.updated_at
          .updated= "Updated at #{@topic.updated_at.to_date}"
        .topic_content= raw @topic.content
      .clear
    = render @posts
  - if can? :create, Post
    .post
      .author= user_info(current_user)
      .content
        = render 'posts/form'
      .clear
= paginate @posts