config/routes.rb
SimpleForum::Application.routes.draw do

  root :to => 'home#index'

  resources :sections, :shallow => true do
    resources :forums, :shallow => true do
      resources :topics, :shallow => true do
        resources :posts
      end
    end
  end

  devise_for :users, :path => "", :controllers => { :registrations => "registrations" },
             :path_names => {  :sign_in => 'login',
                               :sign_out => 'logout',
                               :password => 'secret',
                               :confirmation => 'verification',
                               :unlock => 'unblock',
                               :registration => 'register',
                               :sign_up => 'sign_up' }

  resources :users do
    resources :assets
  end

end

app/models/section.rb
class Section < ActiveRecord::Base
  validates :title, :presence => true

  has_many :forums, :dependent => :destroy
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  load_and_authorize_resource

  def new
  end

  def edit
  end

  def create
    respond_to do |format|
      if @section.save
        format.html { redirect_to(root_path, :notice => 'Section was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @section.update_attributes(params[:section])
        format.html { redirect_to(root_path, :notice => 'Section was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to(root_path) }
    end
  end

end

app/views/sections/_form.html.haml
= form_for @section do |f|
  -if @section.errors.any?
    #error_explanation
      %h2= "#{pluralize(@section.errors.count, "error")} prohibited this forum from being saved:"
      %ul
        - @section.errors.full_messages.each do |msg|
          %li= msg

  .title
    .left= f.label :title
    .left= f.text_field :title
    .clear
  = f.label :description
  = f.text_area :description, :class => "kind_editor", :id => "kind_editor"
  = f.submit 'Save'
= render "shared/editor"

app/views/sections/_section.html.haml
= div_for section do
  .title
    .left= section.title
    - if can? :manage, Forum
      .tool.left= link_to "edit", edit_section_path(section)
      .tool.left= link_to "delete", section, :method => :delete, :confirm => "Are you sure?"
      .tool.right= link_to "New Forum", new_section_forum_path(section)
  = render section.forums

app/views/sections/edit.html.haml
.topic_posts
  #topic_posts_content
    .topic
      .author= user_info(current_user)
      .content
        = render 'form'
      .clear

app/views/sections/new.html.haml
.topic_posts
  #topic_posts_content
    .topic
      .author= user_info(current_user)
      .content
        = render 'form'
      .clear