config/routes.rb
SimpleForum::Application.routes.draw do

  root :to => 'home#index'

  resources :sections, :shallow => true do
    resources :forums, :shallow => true do
      resources :topics, :shallow => true do
        resources :posts
      end
    end
  end

  devise_for :users, :path => "", :controllers => { :registrations => "registrations" },
             :path_names => {  :sign_in => 'login',
                               :sign_out => 'logout',
                               :password => 'secret',
                               :confirmation => 'verification',
                               :unlock => 'unblock',
                               :registration => 'register',
                               :sign_up => 'sign_up' }

  resources :users do
    resources :assets
  end

end

app/models/asset.rb
class Asset < ActiveRecord::Base

  mount_uploader :asset, AssetUploader

  before_save :update_asset_attributes

  belongs_to :user

  validates_presence_of :asset

  def image?
    content_type.include? 'image'
  end

  private

  def update_asset_attributes
    self.content_type = asset.file.content_type
    self.file_size = asset.file.size
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  layout :false
  def new
    @user = current_user
    @asset = Asset.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @user = current_user
    @asset = @user.assets.build(params[:asset])
    respond_to do |format|
      if @asset.save
        format.html # Hacked, put javascript in erb.
      else
        format.html
        format.js
      end
    end
  end

  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/views/assets/_asset.html.haml
= div_for asset do
  .left
    - if asset.image?
      = image_tag(asset.asset_url, :size => "24x24")
    - else
      = image_tag("upload_file.gif", :size => "24x24")
  .left.file_size= "(#{asset.file_size/1024} KB)"
  .operation
    - if asset.image?
      .left.tool= link_to_function "Insert", "KE.insertHtml('kind_editor', '#{image_tag(asset.asset_url)}')"
    - else
      .left.tool= link_to_function "Insert", "KE.insertHtml('kind_editor', '#{link_to image_tag('upload_file.gif'), asset.asset_url}')"
    .left.tool= link_to "Delete", [current_user, asset], :method => :delete, :confirm => "Are you sure?", :remote => true

app/views/assets/_form.html.haml
= form_for [@user, @asset], :remote => true, :html => {:multipart => true, :target => "upload_target#{@asset.id}"} do |f|
  = f.file_field :asset
  %iframe{:id => "upload_target#{@asset.id}", :name => "upload_target#{@asset.id}", :src => "", :style => "width:0;height:0;border:0px solid #fff;"}
  = f.submit 'Upload'

app/views/assets/_form_link.html.haml
.tool= link_to "Upload File", new_user_asset_path(current_user), :remote => true

app/views/assets/_upload_tool.html.haml
#assets
#assets_tool=render "assets/form_link"

app/views/assets/create.html.erb
<%= javascript_include_tag "jquery.min.js" %>
<% if @asset.valid? %>
<script type="text/javascript">
  $(function() {
    $("#assets", parent.document).append("<%= escape_javascript(render @asset) %>");
    $("#assets_tool", parent.document).append("<%= escape_javascript(render 'assets/form_link') %>");
    $("#new_asset", parent.document).remove();
  });
</script>
<% else %>
<script type="text/javascript">
  alert("Invalid Format!");
</script>
<% end %>

app/views/assets/create.js.erb
alert("You must select one file to upload!");

app/views/assets/destroy.js.erb
$("#asset_<%= @asset.id %>").remove();

app/views/assets/new.js.erb
$("#assets").append("<%= escape_javascript(render 'form') %>");
$("#assets_tool .tool").remove();